### ISSUE TITLE
downloader nya gk bisa

### ISSUE THREAD

**Issue by kamlz** [epromite/HisokaBOT-Whatsapp-Bot#2]
vhtear nya di bocchibot jalan aman pake bot ini gk jalan kalo pake /ytmp3 /ytmp4 botnya auto shutdown 
[gambar](https://prnt.sc/wccpmv)

**Comment by kamlz** [comment]
/play sama /tts nya gk bisa balesan robotnya  Ada yang Error! apa saya installnya gag bener kah?

**Comment by epromite** [comment]
Segera saya perbaiki
